version: "3"

services:
  db:
    image: postgres:alpine3.18
    container_name: next_chats_db
    ports:
      - ${DB_PORT}:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: redis:alpine3.19
    container_name: redis_db
    ports:
      - 6379:6379

volumes:
  dbdata:
